In [1]:
import tensorflow as tf
import numpy as np

##### 1) tf.constant():
The created tensors are Immutable (Values can't be changes once created)

In [2]:
scalar = tf.constant(5) # Scalar (Rank 0 Tensor)
print(scalar)
print(scalar.ndim) # Number of dimensions of tensor

tf.Tensor(5, shape=(), dtype=int32)
0


In [3]:
vector = tf.constant([10,10]) # Vector (More than 0 dimension)
print(vector)
print(vector.ndim)

tf.Tensor([10 10], shape=(2,), dtype=int32)
1


In [4]:
mat = tf.constant([[10,2],[10,1]])
print(mat)
print(mat.ndim)

tf.Tensor(
[[10  2]
 [10  1]], shape=(2, 2), dtype=int32)
2


In [5]:
# By default, TensorFlow creates tensors with either an int32 or float32 datatype.
# You can explicitly specify the datatype by passing the dtype argument to the constructor.
tensor = tf.constant([[1,2,3],[4,5,6]], dtype=tf.float64)
print(tensor)
print(tensor.ndim) # A tensor's dimension is also its rank. Hence the above is Rank 2 tensor

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float64)
2


`NOTE`:
- scalar: a single number.
- vector: a number with direction (e.g. wind speed with direction).
- matrix: a 2-dimensional array of numbers.
- tensor: an n-dimensional array of numbers (where n can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector).

##### 2) tf.Variable()
The created tensors are Mutable (Values can be changed)

In [6]:
tensor_var = tf.Variable([1,2,3,4,5], dtype=tf.int16)
print(tensor_var)
tensor_var[2].assign(10)  # To change value of a tensor, you must use "assign" function
tensor_var

<tf.Variable 'Variable:0' shape=(5,) dtype=int16, numpy=array([1, 2, 3, 4, 5], dtype=int16)>


<tf.Variable 'Variable:0' shape=(5,) dtype=int16, numpy=array([ 1,  2, 10,  4,  5], dtype=int16)>

In [7]:
tensor_const = tf.constant([1,2,3,4,5], dtype=tf.int16)
print(tensor_const)
# tensor_const[2].assign(10)  # ERROR

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int16)


##### 3) Create random tensors

In [8]:
# Create random tensors
random_1 = tf.random.Generator.from_seed(42) # set the seed for reproducibility
random_1 = random_1.normal(shape=(3, 2)) # create tensor from a normal distribution 
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

random_1, random_2, random_1 == random_2  # Check if both the tensors are equal

# Seed can also be set throughout the program with np.random.seed(42)

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [9]:
# Random Shuffle of Tensors
tensor_shuf = tf.constant([[1,2],[3,4],[5,6]])
tf.random.shuffle(tensor_shuf)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [3, 4],
       [1, 2]])>

`NOTE`: Global Random Seed vs Operation Random Seed

If we want our shuffled tensors to be shuffled the same way, we should use global seed as well as operation seed

In [10]:
# Shuffle in the same order every time

# Set the global random seed
tf.random.set_seed(42)

# Set the operation random seed
tf.random.shuffle(tensor_shuf, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [11]:
# Set the global random seed
tf.random.set_seed(42) # if you comment this out you'll get different results

# Set the operation random seed
tf.random.shuffle(tensor_shuf)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]])>

Creating tensors with tf

In [12]:
print(tf.ones([10,7]))
print(tf.zeros([1]))


tf.Tensor(
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]], shape=(10, 7), dtype=float32)
tf.Tensor([0.], shape=(1,), dtype=float32)


Tensors from Numpy

In [13]:
import numpy as np
arr = np.arange(6,30,2, dtype=np.int32)
A = tf.constant(arr,shape=[3,4])
arr, A

(array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28]),
 <tf.Tensor: shape=(3, 4), dtype=int32, numpy=
 array([[ 6,  8, 10, 12],
        [14, 16, 18, 20],
        [22, 24, 26, 28]])>)

##### Tensor Info:

- Shape: The length (number of elements) of each of the dimensions of a tensor.
- Rank: The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.
- Axis or Dimension: A particular dimension of a tensor.
- Size: The total number of items in the tensor.

In [14]:
rank_4 = tf.zeros([2, 3, 4, 5])
rank_4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [15]:
rank_4.shape, rank_4.ndim, tf.size(rank_4)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [16]:
print("Datatype of every element:", rank_4.dtype)
print("Number of dimensions (rank):", rank_4.ndim)
print("Shape of tensor:", rank_4.shape)
print("Elements along axis 0 of tensor:", rank_4.shape[0])
print("Elements along last axis of tensor:", rank_4.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


Tensor Indexing

In [17]:
rank_4[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [18]:
# Get the dimension from each index except for the final one
rank_4[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [19]:
test = tf.constant([[1,5],[3,6]])
test[:,1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 6])>

In [20]:
# Adding dimensions to a tensor
rank_3 = test[...,tf.newaxis] # expands the final axis
print(rank_3)
print(tf.expand_dims(test,axis=0)) # new axis in front
print(tf.expand_dims(test,axis=1)) # in middle
print(tf.expand_dims(test,axis=-1)) # expand final axis
test


tf.Tensor(
[[[1]
  [5]]

 [[3]
  [6]]], shape=(2, 2, 1), dtype=int32)
tf.Tensor(
[[[1 5]
  [3 6]]], shape=(1, 2, 2), dtype=int32)
tf.Tensor(
[[[1 5]]

 [[3 6]]], shape=(2, 1, 2), dtype=int32)
tf.Tensor(
[[[1]
  [5]]

 [[3]
  [6]]], shape=(2, 2, 1), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 5],
       [3, 6]])>

Tensor Manipulations:

In [21]:
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [22]:
tensor # unchanged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [23]:
# Multiplication (known as element-wise multiplication)
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

`NOTE`: Using the TensorFlow function (where possible) has the advantage of being sped up later down the line when running as part of a TensorFlow graph.

In [24]:
tf.multiply(tensor, 10)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [25]:
# matrix multiplication
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [26]:
tensor@tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [27]:
a = tf.constant([[1,2],[3,4],[5,6]])
b = tf.constant([[1,2,3],[4,5,6]])
a@b

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])>

In [28]:
# ERROR occurs sinze the matrix is shape is not compatible
# a@a

In [29]:
b = tf.reshape(a,shape=(2,3))

In [30]:
a@b

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])>

In [31]:
print("a reshaped to (2, 3):")
print(tf.reshape(a, (2, 3)), "\n")

print("a transposed:")
print(tf.transpose(a))

a reshaped to (2, 3):
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32) 

a transposed:
tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32)


In [32]:
x = tf.constant([1.7, 7.4])
x.dtype

tf.float32

In [33]:
x = tf.cast(x, dtype=tf.float16)
x.dtype

tf.float16

In [34]:
y = tf.constant([-7, -10])
y

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [35]:
tf.abs(y)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

In [36]:
a = tf.constant(np.random.randint(low=0, high=100, size=50))
a

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([86, 52, 27, 19,  8, 73, 67, 47,  9, 98, 92, 10, 78, 69, 94, 10,  5,
       19, 46, 91, 11, 42, 48, 21, 82, 80,  2, 57, 80, 34, 27, 67,  9, 60,
       76, 12, 69,  4, 54, 41, 17, 72, 61, 16, 60,  1, 12, 70, 43, 64])>

In [37]:
tf.reduce_max(a),tf.reduce_min(a),tf.reduce_mean(a),tf.reduce_sum(a)

(<tf.Tensor: shape=(), dtype=int32, numpy=98>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=45>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2292>)

Positional maximum and minimum

In [38]:
z = tf.constant(np.random.random(50))
z

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.36675299, 0.33090507, 0.96974722, 0.02329247, 0.86394569,
       0.93457399, 0.08524709, 0.70838248, 0.01476626, 0.19416648,
       0.9686959 , 0.46538329, 0.43942092, 0.04751223, 0.88548333,
       0.49777411, 0.1179186 , 0.69351616, 0.70867339, 0.90871557,
       0.32385665, 0.15965396, 0.43283338, 0.55935906, 0.0554054 ,
       0.08565124, 0.58377878, 0.21953793, 0.01270685, 0.94088914,
       0.17660841, 0.99636032, 0.81231053, 0.69768113, 0.8434864 ,
       0.8906927 , 0.27589925, 0.06059358, 0.36628124, 0.72729625,
       0.36452893, 0.58067644, 0.93813811, 0.84545796, 0.66811496,
       0.14912027, 0.90889338, 0.55544598, 0.37815123, 0.69012823])>

In [39]:
tf.argmax(z)

<tf.Tensor: shape=(), dtype=int64, numpy=31>

In [40]:
tf.argmin(z)

<tf.Tensor: shape=(), dtype=int64, numpy=28>

In [41]:
print(f"The maximum value of F is at position: {tf.argmax(z).numpy()}") 
print(f"The maximum value of F is: {tf.reduce_max(z).numpy()}") 
print(f"Using tf.argmax() to index F, the maximum value of F is: {z[tf.argmax(z)].numpy()}")
print(f"Are the two max values the same (they should be)? {z[tf.argmax(z)].numpy() == tf.reduce_max(z).numpy()}")

The maximum value of F is at position: 31
The maximum value of F is: 0.9963603203535546
Using tf.argmax() to index F, the maximum value of F is: 0.9963603203535546
Are the two max values the same (they should be)? True


Squeezing a tensor (removing all single dimensions)

In [42]:
# Create a tensor
w = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
w

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [43]:
# Squeeze the tensor to remove the additional single dimensions (dim of size 1)

w_squeezed = tf.squeeze(w)
w_squeezed, w_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
        0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
        0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
        0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
        0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
        0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
        0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
        0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
        0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
        0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
       dtype=float32)>,
 TensorShape([50]))

One Hot Encoding tensors

In [44]:
# Create a list of indeices
ls = [1,2,3,4]

# one hot encode
tf.one_hot(ls,depth=5)

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [45]:
# specify custom values
tf.one_hot(ls,depth=5, on_value="I love NN", off_value="I like ML")

<tf.Tensor: shape=(4, 5), dtype=string, numpy=
array([[b'I like ML', b'I love NN', b'I like ML', b'I like ML',
        b'I like ML'],
       [b'I like ML', b'I like ML', b'I love NN', b'I like ML',
        b'I like ML'],
       [b'I like ML', b'I like ML', b'I like ML', b'I love NN',
        b'I like ML'],
       [b'I like ML', b'I like ML', b'I like ML', b'I like ML',
        b'I love NN']], dtype=object)>

TF Math Operations

In [46]:
t = tf.range(1,10)
t

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [47]:
tf.square(t)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [48]:
# Sqrt requires non-int type
tf.sqrt(tf.cast(t,tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [49]:
tf.math.log(tf.cast(t,tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

Tenors and NumPy

In [50]:
# Create a tensor directly from a NumPy array
s = tf.constant(np.array([3.,7.,10.,20.]))
s

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([ 3.,  7., 10., 20.])>

In [51]:
np.array(s), type(np.array(s))

(array([ 3.,  7., 10., 20.]), numpy.ndarray)

In [52]:
# Convert tensor s to a NumPy array
s.numpy(), type(s.numpy())

(array([ 3.,  7., 10., 20.]), numpy.ndarray)

In [53]:
# The default types of each are slightly different
numpy_s = tf.constant(np.array([3.,7.,10.,20.]))
tensor_s = tf.constant([3.,7.,10.,20.])

# check the datatypes of each
numpy_s.dtype, tensor_s.dtype

#NOTE: if we create a tensor from numpy,it is in float64. 
# But if we create directly with tf, it is in float32

(tf.float64, tf.float32)

Tensorflow GPU for tensor operations
- Tensors can be processed much faster with GPU and TPU,
hence we use tensors over numpy arrays

In [54]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [55]:
!nvidia-smi

Sun May 21 17:28:44 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 528.24       Driver Version: 528.24       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   52C    P0    16W /  60W |   3181MiB /  4096MiB |     10%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------